services:
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: wpm_db
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rsc-network

  bun_app:
    build: .
    container_name: rsc-wpm-backend
    restart: unless-stopped
    ports:
      - "4001:4001"
    environment:
      DB_HOST: postgres
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: wpm_db
      DB_PORT: 5432
    depends_on:
      - postgres
    networks:
      - rsc-network

  frontend:
    build:
      context: ../_02_rsc_wp_frontend
    container_name: rsc-frontend
    restart: unless-stopped
    environment:
      API_URL: http://bun_app:4001
    depends_on:
      - bun_app
    networks:
      - rsc-network

volumes:
  postgres_data:

networks:
  rsc-network:
    driver: bridge